/** @format */

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/SansSerifFLF-Italic.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/SansSerifFLF-Italic.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CZ Agents",
  description: "Generated by CZ Agents",
  icons: {
    icon: "/images/preview.png",
  },
  openGraph: {
    title: "CZ Agents",
    images: "/images/preview.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
